
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import path from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");

// Получаем DATABASE_URL из переменных окружения
let databaseUrl = env("DATABASE_URL");

// Если это относительный путь для SQLite, преобразуем в абсолютный
if (databaseUrl && databaseUrl.startsWith("file:./")) {
  const relativePath = databaseUrl.replace("file:./", "");
  const absolutePath = path.resolve(projectRoot, relativePath);
  databaseUrl = `file:${absolutePath}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl || env("DATABASE_URL"),
  },
});
