
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";
import path from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// Корень проекта — каталог, где лежит prisma.config.ts
const projectRoot = __dirname;

// Явно загружаем .env из корня проекта — миграции используют ту же БД, что и приложение
dotenv.config({ path: path.join(projectRoot, ".env") });

// Получаем DATABASE_URL (из .env проекта или окружения)
let databaseUrl = process.env.DATABASE_URL || env("DATABASE_URL");

// Если это относительный путь для SQLite, преобразуем в абсолютный
if (databaseUrl && databaseUrl.startsWith("file:./")) {
  const relativePath = databaseUrl.replace("file:./", "");
  const absolutePath = path.resolve(projectRoot, relativePath);
  databaseUrl = `file:${absolutePath}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl || env("DATABASE_URL"),
  },
});
